YOCIMX-10262: udev-rules-imx: Fix bbappend filename
The build is broken by a missing version in the bbappend filename.
```
ERROR: No recipes in default available for:
  /.../sources/meta-nxp-connectivity/imx/meta-imx-bsp/recipes-core/udev/udev-rules-imx.bbappend
```

The upstream recipe now has a version in the filename due to oelint
update, so our bbappend needs to match the filename pattern.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>
Change-Id: I2466c7db15348c48fc5f1136a001c52b8b2db582
Reviewed-on: http://androidsource.nxp.com/project/33517
Reviewed-by: Junmeng Li <junmeng.li_1@nxp.com>