udev-rules-imx: Fix bbappend filename [YOCIMX-10262]
The build is broken by a missing version in the bbappend filename.
```
ERROR: No recipes in default available for:
  /.../sources/meta-nxp-connectivity/imx/meta-imx-bsp/recipes-core/udev/udev-rules-imx.bbappend
```

The upstream recipe now has a version in the filename due to oelint
update, so our bbappend needs to match the filename pattern.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>